import raw from "../data/plugins.json";

/** One catalog entry, mirrored from `site/.vitepress/data/plugins.json`. */
export interface PluginEntry {
  name: string;
  slug: string;
  title: string;
  description: string;
  version: string | null;
  publishedAt: string | null;
  firstPublishedAt: string | null;
  author: string;
  maintainers: string[];
  license: string | null;
  repository: string | null;
  homepage: string | null;
  bugs: string | null;
  npmUrl: string;
  categories: string[];
  keywords: string[];
  unpackedSize: number | null;
  dependencyCount: number;
  peerCount: number;
  installName: string;
  cover: string;
  readme: string | null;
  downloadsLastMonth: number | null;
  featured: boolean;
  source: "local" | "third-party";
}

/** Every plugin in the catalog, as generated by `pnpm docs:scan`. */
export const plugins: PluginEntry[] = (raw as { plugins: PluginEntry[] }).plugins;

/** Categories actually used by the catalog, in a stable order. */
export const usedCategories: string[] = [
  ...new Set(plugins.flatMap((plugin) => plugin.categories)),
].sort((a, b) => a.localeCompare(b));

/** Find one plugin by its URL slug. */
export function pluginBySlug(slug: string): PluginEntry | undefined {
  return plugins.find((plugin) => plugin.slug === slug);
}
