import type { EnvelopeKind } from "../../domain/envelopes/parse.js";

/**
 * A minimal, valid example per envelope kind. Prompts show it so a child sees the exact shape; a
 * test validates every example with the real validators so it can never drift from them.
 */
export const envelopeExamples: Record<EnvelopeKind, unknown> = {
  spec: {
    schemaVersion: 1,
    kind: "spec",
    problem: "...",
    objective: "...",
    users: [{ role: "...", permissions: ["..."] }],
    inScope: ["..."],
    outOfScope: ["..."],
    requirements: [{ id: "R-01", statement: "...", priority: "must" }],
    businessRules: [],
    states: [{ id: "ST-initial", kind: "initial", description: "..." }],
    acceptanceCriteria: [
      {
        id: "AC-01",
        requirementId: "R-01",
        given: "...",
        when: "...",
        // biome-ignore lint/suspicious/noThenProperty: `then` is a field of the spec envelope (given, when, then).
        then: "...",
        critical: true,
      },
    ],
    edgeCases: [],
    accessibility: [],
    performance: [],
    security: [],
    analytics: [],
    assumptions: [],
    openQuestions: [
      {
        id: "Q-01",
        question: "...",
        blocking: false,
        options: ["...", "..."],
        recommendation: "...",
      },
    ],
  },
  "ui-contract": {
    schemaVersion: 1,
    kind: "ui-contract",
    mode: "build",
    surfaces: [{ id: "main-page", route: "/", purpose: "operate" }],
    stateMatrix: [
      {
        stateId: "ST-initial",
        trigger: "...",
        ui: "...",
        actions: [],
        a11y: "...",
        testLevel: ["component"],
      },
    ],
    viewports: [[1024, 640]],
    breakpoints: [{ name: "mobile-max", maxWidth: 599 }],
    elements: [{ id: "primary-cta", locator: { role: "button", name: "..." }, critical: true }],
    componentMap: [{ design: "...", code: "src/shared/ui/Button.tsx", reuse: "reuse" }],
    interactions: [
      { elementId: "primary-cta", on: "activate", result: "...", keyboard: "Enter|Space" },
    ],
    focusOrder: ["primary-cta"],
    fidelityRules: [
      {
        id: "GEO-01",
        requirement: "...",
        kind: "geometry",
        subject: "primary-cta",
        property: "width",
        expected: 160,
        unit: "css_px",
        tolerance: 1,
        severity: "major",
        provenance: "specified",
        verification: "bounding_box",
      },
    ],
    typography: [],
    regions: [],
    masks: [],
    cases: [
      {
        id: "main-desktop-initial",
        surfaceId: "main-page",
        stateId: "ST-initial",
        viewport: [1024, 640],
        theme: "light",
        setup: {},
      },
    ],
    tokensNeeded: [],
    references: [],
    questions: [],
  },
  tokens: {
    schemaVersion: 1,
    kind: "tokens",
    namespace: "",
    roles: [
      {
        token: "--color-action-bg",
        layer: "semantic",
        category: "color",
        purpose: "...",
        status: "new",
      },
    ],
    requiredPairs: [
      {
        fg: "--color-action-fg",
        bg: "--color-action-bg",
        kind: "normal_text",
        states: ["default"],
      },
    ],
    themes: ["light", "dark"],
    generation: { strategy: "catalog", family: "blue", locked: {} },
    rationale: "...",
  },
  plan: {
    schemaVersion: 1,
    kind: "plan",
    summary: "...",
    components: [],
    state: [],
    dataFlow: [],
    contracts: [],
    errors: [],
    dependencies: [],
    adrs: [],
    risks: [],
    architectureConfig: null,
    tasks: [
      {
        id: "T-001",
        title: "...",
        goal: "...",
        layer: "ui",
        files: ["src/example.ts"],
        acceptanceCriteria: ["AC-01"],
        tests: [{ path: "src/example.test.ts", level: "unit" }],
        validation: ["typecheck", "lint", "testRelated"],
        constraints: [],
        dependsOn: [],
        stopConditions: [],
        tdd: "required",
        tddExemptReason: null,
      },
    ],
  },
  "test-map": {
    schemaVersion: 1,
    kind: "test-map",
    entries: [
      {
        acId: "AC-01",
        risk: "...",
        levels: ["component"],
        tests: [{ path: "src/example.test.ts", name: "...", level: "component" }],
        evidence: "...",
        manual: null,
      },
    ],
  },
  "task-result": {
    schemaVersion: 1,
    kind: "task-result",
    taskId: "T-001",
    status: "done",
    summary: "...",
    changedPaths: ["src/example.ts"],
    commands: [{ argv: "pnpm vitest related --run src/example.ts", exitCode: 0, summary: "..." }],
    testFirst: {
      testPath: "src/example.test.ts",
      failingOutputExcerpt: "...",
      passingOutputExcerpt: "...",
    },
    acceptance: [{ acId: "AC-01", satisfiedBy: ["src/example.ts"] }],
    deviations: [],
    questions: [],
    newDependencies: [],
  },
  "a11y-audit": {
    schemaVersion: 1,
    kind: "a11y-audit",
    findings: [
      {
        ruleRef: "FS-A11Y-004",
        wcag: "3.3.2",
        severity: "MAJOR",
        location: { file: "src/example.tsx", line: 1 },
        caseId: null,
        elementId: null,
        evidence: "...",
        fix: "...",
        status: "fail",
      },
    ],
    manualChecks: [
      { criterion: "2.4.3 Focus Order", procedure: "...", result: "not-run", evidence: "" },
    ],
  },
  "fidelity-review": {
    schemaVersion: 1,
    kind: "fidelity-review",
    classifications: [{ findingId: "F-0001", verdict: "defect", rationale: "..." }],
    repairPlan: [{ order: 1, cause: "...", files: ["src/example.css"], findingIds: ["F-0001"] }],
    designCritique: [],
  },
  review: {
    schemaVersion: 1,
    kind: "review",
    findings: [
      {
        dimension: "correctness",
        severity: "MAJOR",
        file: "src/example.ts",
        line: 1,
        claim: "...",
        evidence: "...",
        fix: "...",
        acRef: null,
      },
    ],
    verdict: "changes-requested",
  },
  archive: {
    schemaVersion: 1,
    kind: "archive",
    retrospective: {
      escaped: [],
      detectedBy: [],
      ambiguities: [],
      missingContext: [],
      costlyChecks: [],
      automationCandidates: [],
    },
    ruleCandidates: [],
  },
};
